### ISSUE TITLE
support multiple class selector?

### ISSUE THREAD

**Issue by wjljack** [kristerkari/react-native-postcss-transformer#4]
current , this transformer and css-to-react-native-transform don't support multiple class selector:
```css
.a .b {
background-color:'red'
}
```

how can I solve this problem?
